# Generated by Django 3.2.9 on 2021-11-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='Firstname')),
                ('lname', models.CharField(max_length=50, verbose_name='Lastname')),
                ('is_admin', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('birthdate', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('number', models.IntegerField(blank=True, max_length=15, verbose_name='Mobilenumber')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['lname', 'fname', 'is_admin', 'birthdate'],
            },
        ),
    ]
