# Generated by Django 3.2.9 on 2021-11-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Mobilenumber'),
        ),
    ]
