# Generated by Django 3.2.9 on 2021-11-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_alter_user_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
