# Generated by Django 3.2.9 on 2022-01-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='picture_uploads/'),
        ),
    ]
