# Generated by Django 3.2.9 on 2021-12-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cart_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_elem',
            field=models.CharField(default=-1, max_length=10000),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_ip',
            field=models.CharField(default=-1, max_length=1000),
        ),
    ]
