# Generated by Django 3.2.9 on 2021-12-31 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cart', '0003_auto_20211231_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_elem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_ip',
            field=models.CharField(max_length=1000),
        ),
    ]
