# Generated by Django 3.2.9 on 2022-01-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_auto_20220103_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='items',
            new_name='items_id',
        ),
    ]
