# Generated by Django 3.2.9 on 2022-01-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_rename_items_payment_items_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_img_url',
            field=models.CharField(default='url', max_length=1000),
            preserve_default=False,
        ),
    ]
