# Generated by Django 3.2.9 on 2021-11-29 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
                ('preis', models.DecimalField(decimal_places=2, max_digits=7)),
                ('material', models.CharField(choices=[('G', 'Gold'), ('WG', 'Weissgold'), ('RG', 'Rosegold')], max_length=2)),
                ('ring_Breite', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ring',
                'verbose_name_plural': 'Rings',
                'ordering': ['bezeichnung', '-preis'],
            },
        ),
    ]
