# Generated by Django 3.2.9 on 2021-12-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rings', '0002_comment_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='book',
            new_name='ring',
        ),
    ]
