# Generated by Django 3.2.9 on 2021-12-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rings', '0003_rename_book_vote_ring'),
    ]

    operations = [
        migrations.AddField(
            model_name='ring',
            name='product_img_url',
            field=models.CharField(default='default-url', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ring',
            name='material',
            field=models.CharField(choices=[('GG', 'Gelbgold'), ('WG', 'Weissgold'), ('RG', 'Rosegold')], max_length=2),
        ),
    ]
