# Generated by Django 3.2.9 on 2022-01-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rings', '0005_remove_ring_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ring',
            name='description',
            field=models.CharField(default='Produkt Beschreibung Platzhalter', max_length=1000),
            preserve_default=False,
        ),
    ]
