# Generated by Django 3.2.9 on 2022-01-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rings', '0007_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
