# Generated by Django 3.2.9 on 2022-01-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rings', '0012_ratingevaluation_evaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ring',
            old_name='ring_Breite',
            new_name='ring_size',
        ),
    ]
