# Generated by Django 3.2.9 on 2022-01-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rings', '0013_rename_ring_breite_ring_ring_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='ring',
            name='category',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
