# Generated by Django 3.2.9 on 2022-01-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rings', '0014_auto_20220113_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ring',
            name='product_img_url',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
